add default text for PR
SchibstedSpain/AWSEnums pull request #5
Opened 2017-11-07 12:49 UTC by ferrangrau

@joaoqalves can you review this?

2017-11-09 12:01 UTC, joaoqalves commented on .github/PULL_REQUEST_TEMPLATE.md
> +Please check [this](https://github.schibsted.io/scmspain/devops-ij--aws-infrastructure/pull/306) example
People may not have access to this

2017-11-09 12:01 UTC, joaoqalves requested changes

2017-11-09 12:01 UTC, joaoqalves commented on .github/PULL_REQUEST_TEMPLATE.md
> +Please check [this](https://github.schibsted.io/scmspain/devops-ij--aws-infrastructure/pull/306) example
People may not have access to this

2017-11-09 12:05 UTC, ferrangrau commented on .github/PULL_REQUEST_TEMPLATE.md
> +Please check [this](https://github.schibsted.io/scmspain/devops-ij--aws-infrastructure/pull/306) example
@joaoqalves removed!

2017-11-13 09:37 UTC, joaoqalves approved these changes

2017-11-13 09:40 UTC, merged